# Generated by Django 4.1.1 on 2022-09-20 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blogs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='Auth',
            new_name='Author_name',
        ),
    ]
